version: '{branch}-{build}'

os:
- Visual Studio 2017
- Visual Studio 2019

configuration:
- Release
- Debug

environment:
  matrix:
    - arch: x64
    - arch: x86

init:
  - set arch=
  - if "%arch%"=="x64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set GENERATOR="Visual Studio 16 2019%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set GENERATOR="Visual Studio 15 2017%arch%" )
  - echo %generator%

before_build:
- md build
- cd build
- cmake --config "%CONFIGURATION%" -G "%GENERATOR%" ..

build_script:
- cmake --build . --config "%CONFIGURATION%"

test_script:
- cd bin/%CONFIGURATION%
- CppGoogleTestStarter.exe --gtest_output=xml:test_results.xml
- powershell ../../../scripts/appveyor.ps1