version: '{branch}-{build}'

configuration:
- Release
- Debug

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - ARCH: x64
      GENERATOR: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - ARCH: Win32
      GENERATOR: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

init: []

before_build:
- md build
- cd build
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (cmake --config "%CONFIGURATION%" -G "%GENERATOR%" ..)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (cmake --config "%CONFIGURATION%" -G "%GENERATOR%" -A %ARCH% ..)

build_script:
- cmake --build . --config "%CONFIGURATION%"

test_script:
- cd bin/%CONFIGURATION%
- CppGoogleTestStarter.exe --gtest_output=xml:test_results.xml
- powershell ../../../scripts/appveyor.ps1