version: '{branch}-{build}'

os:
- Visual Studio 2017
- Visual Studio 2019

configuration:
- Release
- Debug

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017
    - GENERATOR: Visual Studio 15 2017 Win64
    - GENERATOR: Visual Studio 16 2019
    - GENERATOR: Visual Studio 16 2019 Win64

init: []

before_build:
- md build
- cd build
- cmake --config "%CONFIGURATION%" -G "%GENERATOR%" ..

build_script:
- cmake --build . --config "%CONFIGURATION%"

test_script:
- cd bin/%CONFIGURATION%
- CppGoogleTestStarter.exe --gtest_output=xml:test_results.xml
- powershell ../../../scripts/appveyor.ps1